# Generated by Django 5.1.4 on 2024-12-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('language', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
