# Generated by Django 5.1.4 on 2024-12-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options_alter_movie_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='homepage',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_company_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='revenue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(default='Released', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
