# Generated by Django 5.1.4 on 2024-12-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_options_movie_budget_movie_genre_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='languages',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_company_id',
            field=models.IntegerField(null=True),
        ),
    ]
