# Generated by Django 5.1.4 on 2024-12-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
