# Generated by Django 5.1.4 on 2024-12-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movie_homepage_alter_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
    ]
